version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Specify the package ecosystems you want to update
  # - package-ecosystem: "npm" # Example: npm, pip, rubygems
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
