name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
    # - cron: "* * * * *"
    # - cron: "0 0 * * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
      - name: DEVCARD
        uses: dailydotdev/action-devcard@2.3.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}


